In [4]:
import numpy as np

data = np.random.normal(0, 1, 10)
data

array([-0.70187382, -0.77287638,  0.40570732, -1.20116135,  0.64280602,
       -1.78833569,  0.56633727, -0.09683136,  0.37421208,  0.78332994])

In [7]:
i1 = np.argmin(data)
i2 = np.argmax(data)
i1, i2, data[i1], data[i2]

(np.int64(5),
 np.int64(9),
 np.float64(-1.7883356899257037),
 np.float64(0.7833299357202902))

In [13]:
np.sort(data)[:3]

array([-1.78833569, -1.20116135, -0.77287638])

In [ ]:
idx = np.argsort(data)
data[idx][:3]

array([-1.78833569, -1.20116135, -0.77287638])

In [14]:
data = np.random.randint(0, 10, (4, 6))
data.shape

(4, 6)

In [15]:
data

array([[8, 3, 3, 5, 2, 3],
       [0, 9, 1, 5, 9, 2],
       [8, 8, 9, 2, 7, 1],
       [3, 3, 6, 3, 1, 1]], dtype=int32)

In [17]:
np.sort(data, axis=0)

array([[0, 3, 1, 2, 1, 1],
       [3, 3, 3, 3, 2, 1],
       [8, 8, 6, 5, 7, 2],
       [8, 9, 9, 5, 9, 3]], dtype=int32)

In [18]:
np.sort(data, axis=1)

array([[2, 3, 3, 3, 5, 8],
       [0, 1, 2, 5, 9, 9],
       [1, 2, 7, 8, 8, 9],
       [1, 1, 3, 3, 3, 6]], dtype=int32)

In [19]:
data = np.random.randint(0, 10, 7)
data

array([6, 7, 1, 1, 7, 8, 4], dtype=int32)

In [7]:
data = np.arange(1, 20)
np.random.shuffle(data)
data

array([ 3, 10,  9,  7,  1, 13, 14, 18, 17,  8, 19, 15, 16,  5,  6,  2, 12,
       11,  4])

In [8]:
import numpy as np

np.partition(data, 3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

# Pandas

In [9]:
np.random.normal(60, 5, (25))

array([61.0136694 , 60.28288186, 64.11447377, 52.61770471, 67.1129859 ,
       65.94761688, 66.78530499, 59.42849103, 57.77538711, 58.54699548,
       61.87780796, 59.58802842, 54.23160277, 56.60968803, 62.9174363 ,
       59.27869465, 57.62346364, 54.78257319, 64.01743038, 59.84591573,
       49.93397879, 56.44554045, 56.6255061 , 66.35106436, 54.21031998])

In [1]:
pip install pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.2/11.3 MB 6.3 MB/s eta 0:00:02
   -- ------------------------------------- 0.7/11.3 MB 8.8 MB/s eta 0:00:02
   --- ------------------------------------ 1.1/11.3 MB 9.7 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/11.3 MB 9.4 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.3 MB 10.3 MB/s eta 0:00:01
   -------- ------------------------------- 2.5/11.3 MB 10.2 MB/s eta 0:00:01
   ----------- ---------------------------- 3.2/11.3 MB 11.4 MB/s eta 0:00:01
   ------------- -------------------------- 3.7/11.3 MB 11.2 MB/s eta 0:00:01
   --------------- ------------------------ 4.4/11.3 MB 11.6 MB/s eta 0:00:01
   ----------------- ---------------------- 5.1/11.3 MB 12.0 MB/s eta 0:00:01
   ------------------- -------------------- 5.4/11.3 MB 11.6 MB/s eta 0:00:01
   -------------------- ------------------- 5.9/11.3 MB 11.8 MB/s eta 0:00:0


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: C:\Users\김준영\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.1'

In [35]:
df = pd.read_csv('iris.csv')

In [36]:
type(df)

pandas.core.frame.DataFrame

In [13]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [17]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.iloc[:, -1]

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [19]:
df.iloc[:, :-1]

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [22]:
col = ['sepal.length','sepal.width','petal.length','petal.width']
X = df[col]
X

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [23]:
y = df.iloc[:, -1]

In [28]:
y.shape, type(y)

((150,), pandas.core.series.Series)

In [26]:
data = df.iloc[:, :-1].values
data.shape

(150, 4)

In [30]:
np.random.normal(0, 1, (150, 4)).shape

(150, 4)

In [33]:
pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])

a    1
b    2
c    3
d    4
dtype: int64

In [34]:
pd.Series([1, 2, 3, 4])

0    1
1    2
2    3
3    4
dtype: int64

In [32]:
d = {
    'a': 1,
    'b': 2,
    'c': 3
}

pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [37]:
d = {
    'a': 1,
    'b': 2,
    'c': 3
}
pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [39]:
df = pd.DataFrame({'d1': d, 'd2': d})

In [40]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [42]:
df.columns

Index(['d1', 'd2'], dtype='object')

In [45]:
df.head()

d1  d2
a   1   1
b   2   2
c   3   3

In [43]:
df['d1']

a    1
b    2
c    3
Name: d1, dtype: int64

In [44]:
df['d2']

a    1
b    2
c    3
Name: d2, dtype: int64

In [46]:
df = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [48]:
idx = pd.Index([1, 2, 3, 4])
idx

Index([1, 2, 3, 4], dtype='int64')

In [53]:
idx[3], idx[-1], idx[1:3]

(np.int64(4), np.int64(4), Index([2, 3], dtype='int64'))

In [55]:
idx.shape, idx.dtype

((4,), dtype('int64'))

In [56]:
idx[1] = 999

TypeError: Index does not support mutable operations

In [57]:
s = 'hello'
s[0] = 'H'

TypeError: 'str' object does not support item assignment

In [58]:
t = (1, 2, 3)
t[0] = 999

TypeError: 'tuple' object does not support item assignment

In [62]:
idx1 = pd.Index([1, 3, 5, 7, 9])
idx2 = pd.Index([2, 3, 5, 7, 11])

idx1.intersection(idx2)

Index([3, 5, 7], dtype='int64')

In [63]:
idx1.union(idx2)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [87]:
df = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [88]:
col1 = df['sepal.length']
type(col1)

pandas.core.series.Series

In [89]:
col1 = df['sepal.length']
col2 = df['sepal.width']

In [90]:
pd.DataFrame({'sepal.length': col1,
              'sepal.width': col2,
              })

sepal.length  sepal.width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [91]:
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width','variety']

In [92]:
df.head()

sepal_length  sepal_width  petal_length  petal_width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [93]:
df.sepal_length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [94]:
df['aaa'] = df['sepal_length'] - df['sepal_width']

In [95]:
df.head()

sepal_length  sepal_width  petal_length  petal_width variety  aaa
0           5.1          3.5           1.4          0.2  Setosa  1.6
1           4.9          3.0           1.4          0.2  Setosa  1.9
2           4.7          3.2           1.3          0.2  Setosa  1.5
3           4.6          3.1           1.5          0.2  Setosa  1.5
4           5.0          3.6           1.4          0.2  Setosa  1.4

In [96]:
data = np.random.normal(0, 1, (3, 5))
data

array([[-1.54966282,  0.35880184,  0.69824592,  0.17522566, -0.85074522],
       [ 1.41454308, -1.39973739, -0.91430599, -0.43293195, -0.0607365 ],
       [-2.46340227, -0.3191304 ,  0.19197465, -0.05511975, -0.38622554]])

In [97]:
data[1, 1:4] == data[1, 1:-1]

array([ True,  True,  True])

In [99]:
df.sepal_length == df['sepal_length']

0      True
1      True
2      True
3      True
4      True
       ... 
145    True
146    True
147    True
148    True
149    True
Name: sepal_length, Length: 150, dtype: bool

In [102]:
isinstance(1, int)

True

In [104]:
data = np.random.normal(0, 1, (3, 5))
data

array([[-1.02528799, -1.08034569,  1.59380395, -0.96641056,  1.12205553],
       [-0.87482383, -0.71997061,  1.16407571,  0.59785976,  2.09522141],
       [ 1.60176933,  0.06040557,  0.39187811,  0.04691703,  1.45228849]])

In [105]:
data[0]

array([-1.02528799, -1.08034569,  1.59380395, -0.96641056,  1.12205553])

In [107]:
df.values[0]

array([5.1, 3.5, 1.4, 0.2, 'Setosa', 1.5999999999999996], dtype=object)

In [108]:
df.head()

sepal_length  sepal_width  petal_length  petal_width variety  aaa
0           5.1          3.5           1.4          0.2  Setosa  1.6
1           4.9          3.0           1.4          0.2  Setosa  1.9
2           4.7          3.2           1.3          0.2  Setosa  1.5
3           4.6          3.1           1.5          0.2  Setosa  1.5
4           5.0          3.6           1.4          0.2  Setosa  1.4

In [115]:
col = ['sepal_length', 'variety']
df[col]

sepal_length    variety
0             5.1     Setosa
1             4.9     Setosa
2             4.7     Setosa
3             4.6     Setosa
4             5.0     Setosa
..            ...        ...
145           6.7  Virginica
146           6.3  Virginica
147           6.5  Virginica
148           6.2  Virginica
149           5.9  Virginica

[150 rows x 2 columns]

In [116]:
df.head()

sepal_length  sepal_width  petal_length  petal_width variety  aaa
0           5.1          3.5           1.4          0.2  Setosa  1.6
1           4.9          3.0           1.4          0.2  Setosa  1.9
2           4.7          3.2           1.3          0.2  Setosa  1.5
3           4.6          3.1           1.5          0.2  Setosa  1.5
4           5.0          3.6           1.4          0.2  Setosa  1.4

In [128]:
df.iloc[:20, [1, 3, 5]]

sepal_width  petal_width  aaa
0           3.5          0.2  1.6
1           3.0          0.2  1.9
2           3.2          0.2  1.5
3           3.1          0.2  1.5
4           3.6          0.2  1.4
5           3.9          0.4  1.5
6           3.4          0.3  1.2
7           3.4          0.2  1.6
8           2.9          0.2  1.5
9           3.1          0.1  1.8
10          3.7          0.2  1.7
11          3.4          0.2  1.4
12          3.0          0.1  1.8
13          3.0          0.1  1.3
14          4.0          0.2  1.8
15          4.4          0.4  1.3
16          3.9          0.4  1.5
17          3.5          0.3  1.6
18          3.8          0.3  1.9
19          3.8          0.3  1.3

In [ ]:
df.loc[:, ['sepal_length':'petal_length' ]]

sepal_length  petal_width
0             5.1          0.2
1             4.9          0.2
2             4.7          0.2
3             4.6          0.2
4             5.0          0.2
..            ...          ...
145           6.7          2.3
146           6.3          1.9
147           6.5          2.0
148           6.2          2.3
149           5.9          1.8

[150 rows x 2 columns]

In [127]:
mask = df['sepal_length'] > 5
df[mask]

sepal_length  sepal_width  petal_length  petal_width    variety  aaa
0             5.1          3.5           1.4          0.2     Setosa  1.6
5             5.4          3.9           1.7          0.4     Setosa  1.5
10            5.4          3.7           1.5          0.2     Setosa  1.7
14            5.8          4.0           1.2          0.2     Setosa  1.8
15            5.7          4.4           1.5          0.4     Setosa  1.3
..            ...          ...           ...          ...        ...  ...
145           6.7          3.0           5.2          2.3  Virginica  3.7
146           6.3          2.5           5.0          1.9  Virginica  3.8
147           6.5          3.0           5.2          2.0  Virginica  3.5
148           6.2          3.4           5.4          2.3  Virginica  2.8
149           5.9          3.0           5.1          1.8  Virginica  2.9

[118 rows x 6 columns]

In [133]:
df[:1]

sepal_length  sepal_width  petal_length  petal_width variety  aaa
0           5.1          3.5           1.4          0.2  Setosa  1.6

In [134]:
df['sepal_length'] + 1

0      6.1
1      5.9
2      5.7
3      5.6
4      6.0
      ... 
145    7.7
146    7.3
147    7.5
148    7.2
149    6.9
Name: sepal_length, Length: 150, dtype: float64

In [135]:
df.head()

sepal_length  sepal_width  petal_length  petal_width variety  aaa
0           5.1          3.5           1.4          0.2  Setosa  1.6
1           4.9          3.0           1.4          0.2  Setosa  1.9
2           4.7          3.2           1.3          0.2  Setosa  1.5
3           4.6          3.1           1.5          0.2  Setosa  1.5
4           5.0          3.6           1.4          0.2  Setosa  1.4

In [173]:
new_df = df.iloc[:, :4].copy()

In [174]:
new_df.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [175]:
np.exp(new_df) / 4

sepal_length  sepal_width  petal_length  petal_width
0       41.005477     8.278863      1.013800     0.305351
1       33.572445     5.021384      1.013800     0.305351
2       27.486793     6.133133      0.917324     0.305351
3       24.871079     5.549488      1.120422     0.305351
4       37.103290     9.149559      1.013800     0.305351
..            ...          ...           ...          ...
145    203.101456     5.021384     45.318060     2.493546
146    136.142978     3.045623     37.103290     1.671474
147    166.285408     5.021384     45.318060     1.847264
148    123.187260     7.491025     55.351604     2.493546
149     91.259367     5.021384     41.005477     1.512412

[150 rows x 4 columns]

In [176]:
new_df.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [177]:
new_df['sepal_length'][1:] / new_df['sepal_width']

0           NaN
1      1.633333
2      1.468750
3      1.483871
4      1.388889
         ...   
145    2.233333
146    2.520000
147    2.166667
148    1.823529
149    1.966667
Length: 150, dtype: float64

In [178]:
new_df['sepal_length'][1:]

1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 149, dtype: float64

In [179]:
 new_df['sepal_width']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [180]:
new_df['sepal_length'][1:].add(new_df['sepal_width'], fill_value=0)

0      3.5
1      7.9
2      7.9
3      7.7
4      8.6
      ... 
145    9.7
146    8.8
147    9.5
148    9.6
149    8.9
Length: 150, dtype: float64

In [181]:
np.sum(new_df.isna()), 'nan', NaN

c:\Users\user\miniconda3\envs\aip\Lib\site-packages\numpy\_core\fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


NameError: name 'NaN' is not defined

In [182]:
new_df['sepal_width'][3] = None

In [183]:
 new_df['sepal_width']

0      3.5
1      3.0
2      3.2
3      NaN
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [184]:
new_df.isna()

sepal_length  sepal_width  petal_length  petal_width
0           False        False         False        False
1           False        False         False        False
2           False        False         False        False
3           False         True         False        False
4           False        False         False        False
..            ...          ...           ...          ...
145         False        False         False        False
146         False        False         False        False
147         False        False         False        False
148         False        False         False        False
149         False        False         False        False

[150 rows x 4 columns]

In [185]:
# df = read_csv('aa.csv')
# df.head()
# df.info()
# df.describe()

In [186]:
new_df.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          NaN           1.5          0.2
4           5.0          3.6           1.4          0.2

In [187]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [188]:
new_df.isna()

sepal_length  sepal_width  petal_length  petal_width
0           False        False         False        False
1           False        False         False        False
2           False        False         False        False
3           False         True         False        False
4           False        False         False        False
..            ...          ...           ...          ...
145         False        False         False        False
146         False        False         False        False
147         False        False         False        False
148         False        False         False        False
149         False        False         False        False

[150 rows x 4 columns]

In [189]:
new_df.dropna()

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
4             5.0          3.6           1.4          0.2
5             5.4          3.9           1.7          0.4
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[149 rows x 4 columns]

In [190]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [170]:
new_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 149 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  149 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  149 non-null    float64
 3   petal_width   149 non-null    float64
dtypes: float64(4)
memory usage: 5.8 KB


In [191]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [192]:
new_df.fillna(0)

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          0.0           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
new_df.fillna()